// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun prisma/seed.ts",
  },
  datasource: {
    // 🎯 BUAT LOCAL DULU DATABASE url: env("DATABASE_URL")
    // url: env("DIRECT_URL"),
    // 🎯 BUAT PROD DENGAN SUPABASE DIRECT url: env("DIRECT_URL"),
    url: env("DATABASE_URL"),
  },
});
